/*
 * User API
 *
 * A notifications proof of concept API
 *
 * API version: 0.1.0
 * Contact: joe@bebo.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"errors"
	"net/http"
)

// NotificationsAPIApiService is a service that implents the logic for the NotificationsAPIApiServicer
// This service should implement the business logic for every endpoint for the NotificationsAPIApi API.
// Include any external packages or services that will be required by this service.
type NotificationsAPIApiService struct {
}

// NewNotificationsAPIApiService creates a default api service
func NewNotificationsAPIApiService() NotificationsAPIApiServicer {
	return &NotificationsAPIApiService{}
}

// AddNotification - adds a new notification
func (s *NotificationsAPIApiService) AddNotification(ctx context.Context, notificationDetails NotificationDetails) (ImplResponse, error) {
	// TODO - update AddNotification with the required logic for this service method.
	// Add api_notifications_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, Id{}) or use other options such as http.Ok ...
	//return Response(201, Id{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	//return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("AddNotification method not implemented")
}

// Ping - tests this api
func (s *NotificationsAPIApiService) Ping(ctx context.Context) (ImplResponse, error) {
	// TODO - update Ping with the required logic for this service method.
	// Add api_notifications_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, PingResponse{}) or use other options such as http.Ok ...
	//return Response(201, PingResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Ping method not implemented")
}
