/*
 * User API
 *
 * A notifications proof of concept API
 *
 * API version: 0.1.0
 * Contact: joe@bebo.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type NotificationSocketMessage struct {

	// describes the database table changed
	Table string `json:"table"`

	// describes the database operation performed
	Operation string `json:"operation"`

	Data NotificationSocketMessageData `json:"data"`
}
