/*
 * Notifications API
 *
 * A notifications proof of concept API
 *
 * API version: 0.1.0
 * Contact: joe@bebo.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	api "github.com/bebo-dot-dev/go-postgres-sockets/server/api"
)

func main() {
	log.Printf("Server started")

	NotificationsAPIApiService := api.NewNotificationsAPIApiService()
	NotificationsAPIApiController := api.NewNotificationsAPIApiController(NotificationsAPIApiService)

	router := api.NewRouter(NotificationsAPIApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
