/*
 * User API
 *
 * A notifications proof of concept API
 *
 * API version: 0.1.0
 * Contact: joe@bebo.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"github.com/bebo-dot-dev/go-postgres-sockets/server/api"
	"github.com/bebo-dot-dev/go-postgres-sockets/server/database"
	"github.com/gorilla/handlers"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")

	listener := database.NewPostgresDbListener()
	listener.Listen()

	service := api.NewNotificationsApiService()
	controller := api.NewNotificationsApiController(service)

	router := api.NewRouter(controller)
	router.PathPrefix("/").Handler(http.FileServer(http.Dir("./cmd/go-postgres-sockets/static/")))

	corsOrigins := handlers.AllowedOrigins([]string{"https://editor.swagger.io"})
	corsHeaders := handlers.AllowedHeaders([]string{"X-Requested-With", "Content-Type", "Authorization"})
	corsMethods := handlers.AllowedMethods([]string{"GET", "POST", "PUT", "HEAD", "OPTIONS"})
	log.Fatal(http.ListenAndServe(":8080", handlers.CORS(corsOrigins, corsHeaders, corsMethods)(router)))
}